# Generated by Django 5.1.3 on 2024-11-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('task', models.TextField(verbose_name='Описание')),
                ('link_proj', models.TextField(verbose_name='Проект')),
                ('link_author', models.TextField(verbose_name='Автор')),
                ('status', models.TextField(verbose_name='Статус')),
                ('priority', models.TextField(verbose_name='Приоритет')),
                ('date_create', models.TextField(verbose_name='Дата создания')),
                ('date_update', models.TextField(verbose_name='Дата обновления')),
                ('period_execution', models.TextField(verbose_name='Срок выполнения')),
                ('tester', models.TextField(verbose_name='Ответсвенный за тестировку')),
            ],
        ),
    ]
