# Generated by Django 5.1.3 on 2024-11-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmember',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskmember',
            name='title',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='name',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='ProjectMember',
        ),
        migrations.DeleteModel(
            name='TaskMember',
        ),
    ]
