# Generated by Django 5.1.3 on 2024-11-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_taskmember_task_remove_taskmember_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
