# Generated by Django 5.1.3 on 2024-11-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_projects_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date_create',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
